// src/pages/ModuleContentPage.jsx
import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import api from "../api";
import SlideViewer from "../components/SlideViewer";
import SlideCarousel from "../components/SlideCarousel";

export default function ModuleContentPage() {
  const { moduleId } = useParams();
  const [module, setModule] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const res = await api.get(`/modules/${moduleId}`);
        setModule(res.data);
      } catch (err) {
        console.error("Failed to load module", err);
        alert("Failed to load module");
      } finally { setLoading(false); }
    }
    if (moduleId) load();
  }, [moduleId]);

  if (loading) return <p className="p-4">Loading module…</p>;
  if (!module) return <p className="p-4">Module not found.</p>;

  const slides = module.autogenerated?.slides || [];

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">{module.title}</h1>
          {module.course && <p className="text-sm text-gray-600">Course: {module.course}</p>}
        </div>
        <Link to={`/courses/${module.course}`} className="text-sm text-primary underline">← Back to course</Link>
      </div>

      <div className="bg-white p-4 rounded shadow">
        <h2 className="font-semibold mb-2">Notes</h2>
        <p className="text-sm text-gray-700 whitespace-pre-line">{module.content || "No notes available."}</p>
      </div>

      <div>
        <h3 className="text-lg font-semibold">Slides</h3>
        {slides.length === 0 ? (
          <p className="text-sm text-gray-500">No slides for this module.</p>
        ) : (
          <>
            <SlideCarousel slides={slides} />
            <div className="mt-4">
              <h4 className="font-semibold mb-2">Open full viewer</h4>
              <SlideViewer slides={slides} />
            </div>
          </>
        )}
      </div>

      <div>
        <h3 className="text-lg font-semibold">Resources</h3>
        {module.attachments && module.attachments.length > 0 ? (
          <ul className="space-y-2">
            {module.attachments.map((a) => (
              <li key={a.public_id} className="flex justify-between items-center border rounded p-2">
                <button onClick={() => window.open(a.url, '_blank')} className="text-primary underline">{a.originalName || a.type || 'Open'}</button>
                <span className="text-xs text-gray-500">Downloads: {a.downloads || 0}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm text-gray-500">No resources uploaded yet.</p>
        )}
      </div>

    </div>
  );
}