import express from 'express';
const router = express.Router();

import Quiz from '../models/Quiz.js';      // NOTE the .js
import Attempt from '../models/Attempt.js'; // NOTE the .js

// Get quiz
router.get('/:id', async (req, res) => {
  try {
    const quiz = await Quiz.findById(req.params.id);
    if (!quiz) return res.status(404).json({ error: 'Quiz not found' });
    res.json(quiz);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Submit quiz answers (basic auto-marking)
router.post('/:id/submit', async (req, res) => {
  try {
    const quiz = await Quiz.findById(req.params.id);
    if (!quiz) return res.status(404).json({ error: 'Quiz not found' });

    const { answers = [], userId } = req.body;
    const results = [];
    let total = 0, score = 0;

    for (const q of quiz.questions) {
      total += q.marks || 1;
      const entry = answers.find(a => a.qid === q.qid) || { answer: null };
      let correct = null;
      let marksObtained = 0;

      if (q.type === 'mcq') {
        correct = entry.answer === q.correctAnswer;
        marksObtained = correct ? q.marks : 0;
      } else if (q.type === 'one-word' || q.type === 'completion') {
        const normalize = s => (s || '').toString().trim().toLowerCase();
        correct = normalize(entry.answer) === normalize(q.correctAnswer);
        marksObtained = correct ? q.marks : 0;
      } else if (q.type === 'essay') {
        correct = null; // manual grading
        marksObtained = 0;
      }

      score += marksObtained;
      results.push({ qid: q.qid, answer: entry.answer, correct, marksObtained });
    }

    const attempt = await Attempt.create({
      user: userId || null,
      quiz: quiz._id,
      answers: results,
      score,
      total,
      submittedAt: new Date()
    });

    res.json({ attemptId: attempt._id, score, total, results });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Admin: create a sample quiz for a module (dev convenience)
router.post('/create', async (req, res) => {
  try {
    const { moduleId, title, questions } = req.body;
    const quiz = await Quiz.create({
      module: moduleId,
      title,
      questions,
      autogenerated: false,
      published: true
    });
    res.json(quiz);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;  // ES Modules export
