// server/worker/generateStub.js
// Enhanced AI stub — generates MCQ, True/False, One-word, Matching quizzes
// Input: draftId, textOrUrl -> returns { notes, slides, quizzes }
export default async function generateStub(draftId, input) {
  const text = (input || '').toString().slice(0, 1000);

  // --- Notes summary ---
  const notes = `AI Notes (AUTO) — summary of input:\n\n${text}\n\n(End of auto summary)`;

  // --- Slides (split into 200-char chunks for simplicity) ---
  const slides = [
    { title: 'Slide 1 - Overview', content: notes.slice(0, 200) },
    { title: 'Slide 2 - Key Points', content: notes.slice(200, 400) },
    { title: 'Slide 3 - Details', content: notes.slice(400, 600) }
  ];

  // --- Quizzes ---
  const quizzes = [
    {
      title: 'Auto-generated MCQ',
      questions: [
        {
          qid: `mcq1-${Date.now()}`,
          type: 'mcq',
          prompt: 'What is the main topic of this draft?',
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
          correctAnswer: 'Option A',
          marks: 1
        }
      ]
    },
    {
      title: 'Auto-generated True/False',
      questions: [
        {
          qid: `tf1-${Date.now()}`,
          type: 'true-false',
          prompt: 'This draft is auto-generated by the system. True or False?',
          correctAnswer: true,
          marks: 1
        }
      ]
    },
    {
      title: 'Auto-generated One-word / Completion',
      questions: [
        {
          qid: `ow1-${Date.now()}`,
          type: 'one-word',
          prompt: 'The draft summary starts with: "AI Notes (AUTO) — summary of ___?"',
          correctAnswer: 'input',
          marks: 1
        }
      ]
    },
    {
      title: 'Auto-generated Matching',
      questions: [
        {
          qid: `match1-${Date.now()}`,
          type: 'matching',
          prompt: 'Match the slides with their content:',
          options: [
            { left: 'Slide 1', right: 'Overview' },
            { left: 'Slide 2', right: 'Key Points' },
            { left: 'Slide 3', right: 'Details' }
          ],
          correctAnswer: [
            { left: 'Slide 1', right: 'Overview' },
            { left: 'Slide 2', right: 'Key Points' },
            { left: 'Slide 3', right: 'Details' }
          ],
          marks: 1
        }
      ]
    }
  ];

  // Simulate async processing
  await new Promise(r => setTimeout(r, 300));

  return { notes, slides, quizzes };
}
