import mongoose from "mongoose";

// Attachment schema (Cloudinary uploads)
const attachmentSchema = new mongoose.Schema({
  url: { type: String, required: true },
  public_id: { type: String },
  resource_type: { type: String },
});

// Quiz schema
const quizSchema = new mongoose.Schema({
  title: { type: String },
  questions: [
    {
      qid: String,
      type: { type: String, default: "mcq" },
      prompt: String,
      options: [String],
      correctAnswer: String,
      marks: { type: Number, default: 1 },
      explanation: String,
    },
  ],
});

// Main Draft Schema
const draftSchema = new mongoose.Schema(
  {
    // Link to module if published
    module: { type: mongoose.Schema.Types.ObjectId, ref: "Module" },

    // Basic draft metadata
    title: { type: String, required: true },
    sourceText: { type: String },

    // Attachments
    attachments: [attachmentSchema],

    // Unified attributes for human + AI notes
    notes: { type: String },

    // Unified slide structure
    slides: [
      {
        title: String,
        content: String,
      },
    ],

    // Unified quiz structure
    quizzes: [quizSchema],

    // ===========================
    // FIX #1 — Add owner field
    // ===========================
    owner: { type: mongoose.Schema.Types.ObjectId, ref: "User" },

    // Keep createdBy for backward compatibility
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },

    // ===========================
    // FIX #2 — Add AI metadata block
    // ===========================
    autogenerated: {
      type: Object,
      default: {},
    },

    // Publication workflow
    status: {
      type: String,
      enum: ["pending", "generated", "reviewed", "published"],
      default: "pending",
    },

    publishedAt: { type: Date },
  },
  { timestamps: true }
);

export default mongoose.model("Draft", draftSchema);
