// server/models/Module.js
import mongoose from "mongoose";

const attachmentSchema = new mongoose.Schema(
  {
    url: String,
    public_id: String,
    type: String,
    originalName: String,
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    uploadedAt: { type: Date, default: Date.now },
    downloads: { type: Number, default: 0 },
  },
  { _id: false }
);

const moduleSchema = new mongoose.Schema(
  {
    course: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Course",
      required: true,
    },

    title: { type: String, required: true },

    // Main readable notes for student
    content: { type: String, default: "" },

    references: [{ type: String }],

    // AI-generated notes, slides, quizzes
    autogenerated: {
      notes: { type: String, default: "" },
      slides: [
        {
          title: { type: String, default: "" },
          content: { type: String, default: "" },
        },
      ],
      quiz: { type: [Object], default: [] },
      metadata: { type: Object, default: {} },
    },

    // ⭐ NEW: link quizzes to this module
    quizzes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Quiz",
      },
    ],

    attachments: {
      type: [attachmentSchema],
      default: [],
    },

    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

export default mongoose.model("Module", moduleSchema);
