// Module.js
import mongoose from 'mongoose';

const moduleSchema = new mongoose.Schema({
  course: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true },
  title: { type: String, required: true },
  content: { type: String }, // store html/markdown or plain text
  references: [String],
  attachments: [{ type: String }], // file ids or urls for later
  autogenerated: { type: Object, default: {} },
  createdAt: { type: Date, default: Date.now }
});

const Module = mongoose.model('Module', moduleSchema);

export default Module;
