// Quiz.js
import mongoose from 'mongoose';

const questionSchema = new mongoose.Schema({
  qid: { type: String, required: true },
  type: { type: String, enum: ['mcq', 'one-word', 'completion', 'essay'], required: true },
  prompt: { type: String, required: true },
  options: [String],
  correctAnswer: mongoose.Schema.Types.Mixed,
  marks: { type: Number, default: 1 },
  explanation: String
}, { _id: false });

const quizSchema = new mongoose.Schema({
  module: { type: mongoose.Schema.Types.ObjectId, ref: 'Module', required: true },
  title: { type: String, required: true },
  questions: [questionSchema],
  autogenerated: { type: Boolean, default: true },
  published: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

const Quiz = mongoose.model('Quiz', quizSchema);

export default Quiz;
