// server/controllers/adminController.js
// Handles admin upload, generate-draft, review, publish
import Draft from '../models/Draft.js';
import Module from '../models/Module.js';
import Quiz from '../models/Quiz.js';
import cloudinary from '../config/cloudinary.js';
import { CloudinaryStorage } from 'multer-storage-cloudinary';
import multer from 'multer';
import generateStub from '../worker/generateStub.js';

// create multer-storage-cloudinary storage (resource_type: auto to accept docs)
const storage = new CloudinaryStorage({
  cloudinary,
  params: {
    folder: 'lumenre_uploads',
    resource_type: 'auto'
  }
});

// multer middleware exported for routes
export const uploadToCloud = multer({ storage });

/**
 * Create a Draft record by uploading a file OR raw text.
 * - If file uploaded: req.file.path contains cloudinary URL
 * - If raw content provided: req.body.content
 * The controller calls generateStub() and stores generated details in Draft.
 */
export const createDraft = async (req, res) => {
  try {
    const { title, moduleId, rawContent } = req.body;

    // ✅ 1. Validate required fields
    if (!req.user) return res.status(401).json({ error: 'Unauthorized' });
    if (!title) return res.status(400).json({ error: 'Title is required' });

    // ✅ 2. Collect Cloudinary attachment metadata (if file uploaded)
    const attachments = [];
    if (req.file) {
      attachments.push({
        url: req.file.path,
        public_id: req.file.public_id || req.file.filename,
        resource_type: req.file.resource_type,
        originalname: req.file.originalname
      });
    }

    // ✅ 3. Create draft record immediately
    const draft = await Draft.create({
      module: moduleId || null,
      title,
      sourceText: rawContent || (req.file ? `Uploaded file: ${req.file.originalname}` : ''),
      attachments,
      createdBy: req.user._id,
      sourceType: req.file ? 'upload' : 'text',
      version: 1,
      status: 'pending'
    });

    // ✅ 4. Trigger AI generation in background (non-blocking)
    (async () => {
      try {
        const input = rawContent || attachments.map(a => a.url).join('\n') || '';
        const generated = await generateStub(draft._id.toString(), input);

        // Update draft with generated content
        draft.notes = generated.notes || '';
        draft.slides = generated.slides || [];
        draft.quizzes = generated.quizzes || [];
        draft.status = 'generated';
        await draft.save();

        console.log(`[AI Generator] Draft ${draft._id} generated successfully.`);
      } catch (aiErr) {
        console.error(`[AI Generator] Failed for draft ${draft._id}:`, aiErr.message);
        draft.status = 'error';
        draft.errorMessage = aiErr.message;
        await draft.save();
      }
    })();

    // ✅ 5. Respond immediately to user
    return res.status(202).json({
      message: 'Draft created. AI generation started.',
      draftId: draft._id,
      status: draft.status
    });

  } catch (err) {
    console.error('createDraft', err);
    return res.status(500).json({ error: 'Server error creating draft', details: err.message });
  }
};


// List drafts (admin)
export const listDrafts = async (req, res) => {
  try {
    const drafts = await Draft.find().sort({ createdAt: -1 }).populate('createdBy', 'name email');
    res.json(drafts);
  } catch (err) {
    console.error('listDrafts', err);
    res.status(500).json({ error: err.message });
  }
};

// Get single draft
export const getDraft = async (req, res) => {
  try {
    const draft = await Draft.findById(req.params.id).populate('createdBy', 'name email');
    if (!draft) return res.status(404).json({ error: 'Draft not found' });
    res.json(draft);
  } catch (err) {
    console.error('getDraft', err);
    res.status(500).json({ error: err.message });
  }
};

/**
 * Publish: append notes to Module.content (or create module) and create Quizzes
 * Body (optional): { moduleId } if draft has no module
 */
export const publishDraft = async (req, res) => {
  try {
    const draft = await Draft.findById(req.params.id);
    if (!draft) return res.status(404).json({ error: 'Draft not found' });

    const moduleId = draft.module?.toString() || req.body.moduleId;
    if (!moduleId) return res.status(400).json({ error: 'moduleId is required to publish' });

    const mod = await Module.findById(moduleId);
    if (!mod) return res.status(404).json({ error: 'Module not found' });

    // Append generated notes to module content for review
    mod.content = ((mod.content || '') + '\n\n' + (draft.notes || '')).trim();
    mod.autogenerated = mod.autogenerated || {};
    mod.autogenerated.slides = draft.slides;
    mod.autogenerated.attachments = draft.attachments;
    await mod.save();

    // Create quizzes (if any)
    const created = [];
    if (Array.isArray(draft.quizzes)) {
      for (const qset of draft.quizzes) {
        const q = await Quiz.create({
          module: mod._id,
          title: qset.title || `Auto: ${draft.title}`,
          questions: (qset.questions || []).map((qq, idx) => ({
            qid: qq.qid || `q-${idx + 1}-${Date.now()}`,
            type: qq.type || 'mcq',
            prompt: qq.prompt || qq.question || 'Question',
            options: qq.options || qq.choices || [],
            correctAnswer: qq.correctAnswer,
            marks: qq.marks || 1,
            explanation: qq.explanation || ''
          })),
          autogenerated: true,
          published: true
        });
        created.push(q);
      }
    }

    draft.status = 'published';
    draft.publishedAt = new Date();
    await draft.save();

    return res.json({ message: 'Draft published', module: mod, quizzes: created });
  } catch (err) {
    console.error('publishDraft', err);
    res.status(500).json({ error: err.message });
  }
};
